spring.application.name=s19d2

# Server port
server.port=9000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=bank
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Basic Auth (Görev 4)
spring.security.user.name=admin
spring.security.user.password=1234